# Generated by Django 3.1.13 on 2021-11-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='post_body',
            new_name='posting_body',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='post_title',
            new_name='posting_title',
        ),
    ]
