# Generated by Django 3.1.13 on 2021-11-10 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211110_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='posting_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
