# Generated by Django 3.1.13 on 2021-11-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_posting_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='posting_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='posting_title',
            field=models.CharField(max_length=128),
        ),
    ]
