# Generated by Django 3.1.13 on 2021-11-16 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20211115_1339'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
